# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`AtteanX-Compatibility-Trine`
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
        :runtime-requirement    [ :on "Attean 0.019"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

